In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import json

data = pd.read_csv('train.csv')
data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.10,0.90,7,286,4,0,1,0,sales,low
1,0.89,0.93,4,249,3,0,0,0,sales,low
2,0.38,0.50,2,132,3,0,1,0,accounting,low
3,0.95,0.71,4,151,4,0,0,0,sales,medium
4,0.84,0.84,5,163,3,0,0,0,technical,low

In [2]:
print data.shape

(11238, 10)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    data,
    data.left,
    test_size=0.2,
    random_state=0)

print len(X_train)

8990

In [4]:
#map_range_sl = lambda x : '<=0.37' if x <= 0.37 else ('>0.37 and <=0.51' if x <= 0.51 else ('>0.51 and <=0.64' if x<=0.64 else ('>0.64 and <=0.76' if x<=0.76 else ('>0.76 and <=0.87' if x<=0.87 else '>0.87'))))
map_range_sl = lambda x: '<=0.17' if x<=0.17 else ('0.18 to 0.29' if x <= 0.29 else ('0.30 to 0.39' if x<=0.39 else ('0.40 to 0.46' if x<=0.46 else ('0.47 to 0.53' if x<=0.53 else ('0.54 to 0.6' if x<=0.6 else ('0.61 to 0.67' if x<=0.67 else ('0.68 to 0.74' if x<=0.74 else ('0.75 to 0.8' if x<=0.8 else ('0.81 to 0.87' if x<=0.87 else ('0.88 to 0.94' if x<=0.94 else '>0.94'))))))))))
X_train.satisfaction_level = X_train.satisfaction_level.apply(map_range_sl)
X_test.satisfaction_level = X_test.satisfaction_level.apply(map_range_sl)

# map_range_le = lambda x : '<=0.52' if x <= 0.52 else ('>0.52 and <=0.61' if x <= 0.61 else ('>0.61 and <=0.72' if x<=0.72 else ('>0.72 and <=0.83' if x<=0.83 else ('>0.83 and <=0.91' if x<=0.91 else '>0.91'))))
map_range_le = lambda x: '<=0.44' if x<=0.44 else ('0.45 to 0.51' if x <= 0.51 else ('0.52 to 0.58' if x<=0.58 else ('0.59 to 0.65' if x<=0.65 else ('0.66 to 0.71' if x<=0.71 else ('0.72 to 0.78' if x<=0.78 else ('0.79 to 0.86' if x<=0.86 else ('0.87 to 0.93' if x<=0.93 else '>0.93'))))))) 
X_train.last_evaluation = X_train.last_evaluation.apply(map_range_le)
X_test.last_evaluation = X_test.last_evaluation.apply(map_range_le)

# map_range_np = lambda x : '<=3' if x <=3 else ('>3 and <=6' if x<=6 else '>6')
map_range_np = lambda x: '<=3' if x<=3 else '>3'
X_train.number_project = X_train.number_project.apply(map_range_np)
X_test.number_project = X_test.number_project.apply(map_range_np)

# map_range_amh = lambda x : '<=156' if x <=156 else ('>156 and <=199' if x<=199 else ('>199 and <=245' if x<=245 else '>245'))
map_range_amh = lambda x: '<=173' if x<=173 else ('174 to 229' if x<=229 else '>229')
X_train.average_montly_hours = X_train.average_montly_hours.apply(map_range_amh)
X_test.average_montly_hours = X_test.average_montly_hours.apply(map_range_amh)

map_range_ts = lambda x : '<=3' if x <=3 else ('>3 and <=6' if x<=6 else '>6')
X_train.time_spend_company = X_train.time_spend_company.apply(map_range_ts)
X_test.time_spend_company = X_test.time_spend_company.apply(map_range_ts)

/home/tarunm/.local/lib/python2.7/site-packages/pandas/core/generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [5]:
X_train.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
1994,0.75 to 0.8,0.59 to 0.65,>3,>229,<=3,0,0,0,sales,low
2032,0.68 to 0.74,0.52 to 0.58,>3,<=173,<=3,0,0,0,hr,low
883,0.54 to 0.6,0.45 to 0.51,<=3,<=173,>3 and <=6,0,0,0,support,low
7069,0.47 to 0.53,>0.93,<=3,174 to 229,>3 and <=6,1,0,0,IT,low
10426,0.18 to 0.29,0.79 to 0.86,<=3,174 to 229,>3 and <=6,0,0,0,IT,low

In [6]:
def create_tree_node(value, is_leaf):
    new_node = dict()
    new_node['value'] = value
    new_node['is_leaf'] = is_leaf
    new_node['children'] = dict()
    return new_node

In [7]:
def display_tree(t,index):
    print t
    tabs = ''
    for i in range(0,index):
        tabs+='\t'
    print tabs+str(t['value'])
    for c in t['children']:
        i = (index+1)
        display_tree(c,i)

In [8]:
def compute_impurity(pos_ratio,neg_ratio,impurity_function):
    if impurity_function == 'entropy':
        if pos_ratio == 0 or pos_ratio == 1:
            return 0
        else:
            return -((pos_ratio*np.log(pos_ratio)) + (neg_ratio*np.log(neg_ratio)))
    elif impurity_function == 'gini_index':
        return (2*pos_ratio*neg_ratio)
    elif impurity_function == 'misclassification_rate':
        return min(pos_ratio,neg_ratio)
    return 0

In [9]:
def print_tree(curr_data,curr_parent_object,curr_condition, exclude_cols,decision_tree,impurity_function):
    
    curr_parent_str = curr_parent_object['value']
    if curr_parent_str not in exclude_cols:
        exclude_cols.append(curr_parent_str)
    #print 'Current Parent object : '+str(curr_parent_object)
    #print 'Current Condition : '+str(curr_condition)
    m = len(curr_data)
    G = dict()
    for col in curr_data:
        if col in exclude_cols:
            continue
        I = 0.0
        col_pos = 0
        col_neg = 0
        int_info = 0
        for categ in curr_data[col].unique():
            #print 'col :: '+col+' ; categ :: '+str(categ)
            #print curr_data.groupby([col])['left'].value_counts()[categ]
            pos = 0
            neg = 0
            if 1 in curr_data.groupby([col])['left'].value_counts()[categ]: 
                pos = curr_data.groupby([col])['left'].value_counts()[categ][1]
            if 0 in curr_data.groupby([col])['left'].value_counts()[categ]:
                neg = curr_data.groupby([col])['left'].value_counts()[categ][0]
            col_pos += pos
            col_neg += neg
            pos_ratio = float(pos)/float(pos+neg)
            neg_ratio = float(neg)/float(pos+neg)
            impurity = compute_impurity(pos_ratio,neg_ratio, impurity_function)
            Si_S = float(pos+neg)/float(m) 
            I += Si_S*impurity
            int_info += Si_S*np.log(Si_S)
        col_pos_ratio = float(col_pos)/float(col_pos+col_neg)
        col_neg_ratio = float(col_neg)/float(col_pos+col_neg)
        E = compute_impurity(col_pos_ratio,col_neg_ratio,impurity_function)
        G[col] = ((E-I)/(-1*int_info))
    
    if not G:
        if curr_parent_str == 'dummy_parent':
            return decision_tree
        for categ in curr_data[col].unique():
            if 0 in curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition] and 1 in curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition]:
                if curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition][0] > curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition][1]:
                    #print 'Left'
                    new_node = create_tree_node('0',True)
                    curr_parent_object['children'][curr_condition] = new_node
                else:
                    new_node = create_tree_node('1',True)
                    curr_parent_object['children'][curr_condition] = new_node
            elif 0 in curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition]:
                new_node = create_tree_node('0',True)
                curr_parent_object['children'][curr_condition] = new_node
            elif 1 in curr_data.groupby([curr_parent_str])['left'].value_counts()[curr_condition]:
                new_node = create_tree_node('1',True)
                curr_parent_object['children'][curr_condition] = new_node
            else:
                new_node = create_tree_node('0',True)
                curr_parent_object['children'][curr_condition] = new_node
        return decision_tree
    
    max_col = max(G, key=G.get)
    new_node = None
#     res_list = list()
#     for cond in curr_data[max_col].unique():
#         if 0 in curr_data.groupby([max_col])['left'].value_counts()[cond]:
#             res_list.append(curr_data.groupby([max_col])['left'].value_counts()[cond][0])
#         else:
#             res_list.append(0)
#         if 1 in curr_data.groupby([max_col])['left'].value_counts()[cond]:
#             res_list.append(curr_data.groupby([max_col])['left'].value_counts()[cond][1])
#         else:
#             res_list.append(0)
#         res_sum = sum(res_list)
#         if res_sum == 0:
#             new_node = create_tree_node('0',True)
#         else:
#             ratio = max(res_list)/res_sum
#             if ratio > 0.95:
#                 if res_list[0] == max(res_list):
#                     new_node = create_tree_node('0',True)
#                 else:
#                     new_node = create_tree_node('1',True)
    
    if new_node is None:
        new_node = create_tree_node(max_col,False)
    if decision_tree is None:
        decision_tree = new_node
    else:
        curr_parent_object['children'][curr_condition] = new_node
    
    
    if new_node['is_leaf']:
        return
    
    
    temp_exclude_cols = exclude_cols[:]
    for cond in curr_data[max_col].unique():
        print_tree(curr_data.loc[curr_data[max_col]==cond].copy() , new_node, cond,temp_exclude_cols,decision_tree,impurity_function)
    
    return decision_tree

In [10]:
decision_tree_entropy = None
decision_tree_gini = None
decision_tree_mr = None
dummy_node = dict()
dummy_node['value'] = 'dummy_parent'
decision_tree_entropy = print_tree(X_train.copy(),dummy_node,'dummy_condition',['left'],decision_tree_entropy,'entropy')
decision_tree_gini = print_tree(X_train.copy(),dummy_node,'dummy_condition',['left'],decision_tree_gini,'gini_index')
decision_tree_mr = print_tree(X_train.copy(),dummy_node,'dummy_condition',['left'],decision_tree_mr,'misclassification_rate')
# print json.dumps(decision_tree_entropy)

/home/tarunm/.local/lib/python2.7/site-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in double_scalars

In [11]:
def validate_row(row,tree_node):
    if tree_node['is_leaf']:
        if row['left'] == 1 and tree_node['value'] == '1':
            #true positive
            return 2
        elif row['left'] == 1 and tree_node['value'] == '0':
            #false negative
            return -1
        elif row['left'] == 0 and tree_node['value'] == '1':
            #false positive
            return 0
        elif row['left'] == 0 and tree_node['value'] == '0':
            #true negative
            return 1
    key = tree_node['value']
    val = row[key]
    if val not in tree_node['children']:
        #error considered as true negative
        return 1
    else:
        return validate_row(row,tree_node['children'][val])

In [12]:
def display_performance_metrics(X,tree):
    m = len(X)
    hits = 0
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    for index,row in X.iterrows():
        verdict = validate_row(row,tree)
        if verdict == -1:
            fn += 1
        elif verdict == 0:
            fp += 1
        elif verdict == 1:
            hits += 1
            tn += 1
        elif verdict == 2:
            hits += 1
            tp += 1
    
    accuracy = float(hits)/float(m)
    misclassification = 1.0 - accuracy
    print 'Accuracy : '+str(accuracy*100)
    print 'Misclassification error : '+str(misclassification * 100)
    precision = float(tp)/(float(tp)+float(fp))
    recall = float(tp)/(float(tp)+float(fn))
    print 'Precision : '+str(precision)
    print 'Recall : '+str(recall)

    f1_score = 2.0/((1.0/recall)+(1.0/precision))
    print 'F1 score : '+str(f1_score)

In [13]:
X_validation, X_temp, y_validation, y_temp = train_test_split(
    X_train,
    X_train.left,
    test_size=0.1,
    random_state=0)
print '************TRAIN PERFORMANCE*************'
print
print '::::Impurity Function : Entropy::::'
print
display_performance_metrics(X_train,decision_tree_entropy)
print '******************'
print
print '::::Impurity Function : Gini Index::::'
print
display_performance_metrics(X_validation,decision_tree_gini)
print '******************'
print
print '::::Impurity Function : Misclassification rate::::'
print
display_performance_metrics(X_validation,decision_tree_mr)
print '******************'

************TRAIN PERFORMANCE*************

::::Impurity Function : Entropy::::

Accuracy : 98.8876529477
Misclassification error : 1.11234705228
Precision : 0.957941834452
Recall : 0.997205402888
F1 score : 0.977179370151
******************

::::Impurity Function : Gini Index::::

Accuracy : 98.838215301
Misclassification error : 1.16178469905
Precision : 0.956005931784
Recall : 0.997421351212
F1 score : 0.976274608783
******************

::::Impurity Function : Misclassification rate::::

Accuracy : 98.838215301
Misclassification error : 1.16178469905
Precision : 0.956005931784
Recall : 0.997421351212
F1 score : 0.976274608783
******************

In [14]:
print '************TEST PERFORMANCE*************'
print
print '::::Impurity Function : Entropy::::'
print
display_performance_metrics(X_test,decision_tree_entropy)
print '******************'
print
print '::::Impurity Function : Gini Index::::'
print
display_performance_metrics(X_test,decision_tree_gini)
print '******************'
print
print '::::Impurity Function : Misclassification rate::::'
print
display_performance_metrics(X_test,decision_tree_mr)
print '******************'

************TEST PERFORMANCE*************

::::Impurity Function : Entropy::::

Accuracy : 98.3985765125
Misclassification error : 1.60142348754
Precision : 0.937621832359
Recall : 0.99175257732
F1 score : 0.963927855711
******************

::::Impurity Function : Gini Index::::

Accuracy : 98.3985765125
Misclassification error : 1.60142348754
Precision : 0.937621832359
Recall : 0.99175257732
F1 score : 0.963927855711
******************

::::Impurity Function : Misclassification rate::::

Accuracy : 98.3985765125
Misclassification error : 1.60142348754
Precision : 0.937621832359
Recall : 0.99175257732
F1 score : 0.963927855711
******************